export const CATEGORY_LABELS: Record<string, string> = {
  OTT: "OTT & TV",
  MUSIC: "Music & Audio",
  SHOPPING: "Shopping",
  FOOD_DELIVERY: "Food & Delivery",
  PHARMACY: "Pharmacy",
  HEALTHCARE: "Healthcare",
  TRAVEL: "Travel",
  AIRPORT_LOUNGE: "Airport Lounge",
  MOVIES: "Movies",
  FITNESS: "Fitness & Wellness",
  SOFTWARE: "Software & Productivity",
  EDUCATION: "Education & Learning",
  HOTEL: "Hotels",
  CREDIT_CARD_BENEFITS: "Credit Card Benefits",
  OTHER: "Other",
};

export const CATEGORY_PROVIDERS: Record<string, string[]> = {
  OTT: [
    "Netflix", "Amazon Prime Video", "Disney+ Hotstar", "SonyLIV", "ZEE5",
    "JioHotstar", "Sun NXT", "Aha", "Hoichoi", "Lionsgate Play",
    "Apple TV+", "YouTube Premium", "Crunchyroll", "Discovery+", "MX Player",
  ],
  MUSIC: [
    "Spotify", "YouTube Music", "Apple Music", "Amazon Music", "JioSaavn",
    "Gaana", "Wynk Music", "Audible", "Storytel", "Pocket FM",
  ],
  SHOPPING: [
    "Amazon Prime", "Flipkart VIP", "Myntra Insider", "AJIO",
    "Tata CLiQ", "Nykaa Prive", "FirstCry", "Pothys",
  ],
  FOOD_DELIVERY: [
    "Swiggy One", "Zomato Gold", "Blinkit", "Zepto Pass", "BigBasket", "Tata NeuPass",
  ],
  PHARMACY: [
    "Tata 1mg", "PharmEasy", "Netmeds", "Apollo 24|7",
    "Practo", "HealthKart", "MediBuddy", "MedPlus",
  ],
  HEALTHCARE: [
    "Apollo", "Practo", "MediBuddy", "HealthifyMe", "Cult.fit", "Tata 1mg",
  ],
  TRAVEL: [
    "MakeMyTrip", "Cleartrip", "EaseMyTrip", "Booking.com",
    "Airbnb", "Agoda", "Marriott Bonvoy", "Accor ALL",
  ],
  AIRPORT_LOUNGE: [
    "Priority Pass", "DreamFolks", "LoungeKey", "Plaza Premium", "Amex Lounge",
  ],
  MOVIES: [
    "BookMyShow", "PVR INOX", "Cinepolis", "PVR", "INOX",
  ],
  FITNESS: [
    "Cult.fit", "HealthifyMe", "Fittr", "Nike Training Club",
    "Strava", "Headspace", "Calm", "MyFitnessPal",
  ],
  SOFTWARE: [
    "Microsoft 365", "Adobe Creative Cloud", "Canva Pro", "Notion",
    "Evernote", "Grammarly", "Todoist", "Slack", "Zoom", "Dropbox",
  ],
  EDUCATION: [
    "Coursera Plus", "Udemy", "LinkedIn Learning", "Skillshare",
    "MasterClass", "Brilliant", "Duolingo Super", "DataCamp", "Pluralsight",
  ],
  HOTEL: [
    "Marriott Bonvoy", "Hilton Honors", "Accor ALL", "Taj", "ITC Hotels", "IHG", "Hyatt",
  ],
  CREDIT_CARD_BENEFITS: [
    "HDFC Bank", "ICICI Bank", "Axis Bank", "SBI Card", "Amex", "Kotak",
  ],
  OTHER: [],
};

export const PROVIDER_SLUGS: Record<string, string> = {
  Netflix: "netflix",
  "Amazon Prime Video": "primevideo",
  "Disney+ Hotstar": "disneyplus",
  "Apple TV+": "appletv",
  "YouTube Premium": "youtube",
  "YouTube Music": "youtubemusic",
  Crunchyroll: "crunchyroll",
  "Discovery+": "discoveryplus",
  "Lionsgate Play": "lionsgateplay",
  SonyLIV: "sonyliv",
  ZEE5: "zee5",
  JioHotstar: "jiohotstar",
  "Sun NXT": "sunnxt",
  Aha: "aha",
  Hoichoi: "hoichoi",
  Spotify: "spotify",
  "Apple Music": "applemusic",
  "Amazon Music": "amazonmusic",
  JioSaavn: "jiosaavn",
  Gaana: "gaana",
  "Wynk Music": "wynk",
  Audible: "audible",
  Storytel: "storytel",
  "Pocket FM": "pocketfm",
  "Microsoft 365": "microsoft",
  "Adobe Creative Cloud": "adobe",
  "Canva Pro": "canva",
  Notion: "notion",
  Evernote: "evernote",
  Grammarly: "grammarly",
  Todoist: "todoist",
  Slack: "slack",
  Zoom: "zoom",
  Dropbox: "dropbox",
  "Amazon Prime": "amazon",
  "Swiggy One": "swiggy",
  "Zomato Gold": "zomato",
  Blinkit: "blinkit",
  "Zepto Pass": "zepto",
  BigBasket: "bigbasket",
  "Tata NeuPass": "tataneu",
  "Flipkart VIP": "flipkart",
  "Myntra Insider": "myntra",
  AJIO: "ajio",
  "Tata CLiQ": "tatacliq",
  "Nykaa Prive": "nykaa",
  FirstCry: "firstcry",
  "Tata 1mg": "tata1mg",
  PharmEasy: "pharmeasy",
  Netmeds: "netmeds",
  "Apollo 24|7": "apollo",
  Practo: "practo",
  HealthKart: "healthkart",
  MediBuddy: "medibuddy",
  MedPlus: "medplus",
  "Cult.fit": "cultfit",
  HealthifyMe: "healthifyme",
  Fittr: "fittr",
  "Nike Training Club": "nike",
  Strava: "strava",
  Headspace: "headspace",
  Calm: "calm",
  MyFitnessPal: "myfitnesspal",
  MakeMyTrip: "makemytrip",
  Cleartrip: "cleartrip",
  EaseMyTrip: "easemytrip",
  "Booking.com": "bookingdotcom",
  Airbnb: "airbnb",
  Agoda: "agoda",
  "Marriott Bonvoy": "marriott",
  "Accor ALL": "accor",
  "Hilton Honors": "hilton",
  Taj: "tajhotels",
  "ITC Hotels": "itchotels",
  IHG: "ihg",
  Hyatt: "hyatt",
  "HDFC Bank": "hdfcbank",
  "ICICI Bank": "icicibank",
  "Axis Bank": "axisbank",
  "SBI Card": "sbicard",
  Amex: "americanexpress",
  Kotak: "kotak",
  "Coursera Plus": "coursera",
  Udemy: "udemy",
  "LinkedIn Learning": "linkedin",
  Skillshare: "skillshare",
  MasterClass: "masterclass",
  Brilliant: "brilliant",
  "Duolingo Super": "duolingo",
  DataCamp: "datacamp",
  Pluralsight: "pluralsight",
  BookMyShow: "bookmyshow",
  "PVR INOX": "pvrinox",
  Cinepolis: "cinepolis",
  "Priority Pass": "prioritypass",
  DreamFolks: "dreamfolks",
  LoungeKey: "loungekey",
};

export const PROVIDER_DOMAINS: Record<string, string> = {
  Pothys: "pothys.com",
  "Plaza Premium": "plazapremiumlounge.com",
  "Amex Lounge": "americanexpress.com",
  PVR: "pvrcinemas.com",
  INOX: "inoxmovies.com",
};